### ISSUE TITLE
ffmpeg 4.3.2

### ISSUE THREAD

**Issue by GyanD** [AndreAugustoDev/chocolatey-packages#1]
I assume the ffmpeg package submitted for moderation at https://chocolatey.org/packages/ffmpeg-shared/4.3.2.20210202 is by you.

The ffmpeg release maintainer did not include all changes for 4.3.2 when they made the release initially. The remaining changes were added on 20th Feb. I've updated my release variants. I suggest you withdraw the 2021-02-02 submission and submit the 2021-02-20 package for inclusion.

Thanks,
Gyan

**Comment by AndreAugustoDev** [comment]
Hello
Thanks for the issue
The package has already been updated, and future versions will be updated automatically using AU and AppVeyor
